name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Tests on PHP ${{ matrix.php }} with php-cs-fixer ${{ matrix.cs-fixer }}

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        php: [7.4, 8.0]
        # Make sure we're testing with the lowest supported cs-fixer too because we're currently using @internal marked classes and those can break any time.
        cs-fixer: [2.16.8, ^2.16.8]
        exclude:
          - php: 8.0
            cs-fixer: 2.16.8

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: |
          composer require "friendsofphp/php-cs-fixer=${{ matrix.cs-fixer }}" --no-update
          composer install --dev --prefer-dist --no-progress --no-suggest
      
      - name: Execute tests
        run: vendor/bin/pest --colors=always

  code-style:
    name: Code style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --dev --prefer-dist --no-progress --no-suggest --working-dir=tools/php-cs-fixer

      - name: Run php-cs-fixer
        run: composer cs-fix -- --dry-run --diff --using-cache=no --diff-format udiff